version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: enmediotest-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'secret'
      MONGO_INITDB_DATABASE: produc
    volumes:
      - ./init/init-script.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    container_name: enmediotest-expresMongo
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongo'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'secret'
      ME_CONFIG_MONGODB_PORT: '27017'
      ME_CONFIG_BASICAUTH_USERNAME: 'sa'
      ME_CONFIG_BASICAUTH_PASSWORD: 'sa'
    links:
      - mongo    
    ports:
      - "8081:8081"


# node-app:
#     image: nodeimage
#     container_name: enmediotest-app
#     build: .
#     ports:
#       - "8082:8082"
#     environment:
#       - PORT=8082
#       - MONGO_USERNAME = 'sa'
#       - MONGO_PASSWORD = 'sa'
#       - MONGO_HOSTNAME = '127.0.0.1'
#       - MONGO_PORT = '27017'
#       - MONGO_DB = 'produc'